/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.ui;

import javax.swing.JOptionPane;

import main.basedata.BillDataBase;
import main.maintain.BillManagement;
import main.maintain.ParkSpaceManagement;

/**
 *
 * @author jiang_yq
 */
public class ExitFrame extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3291016282813346280L;

	/**
	 * Creates new form ExitFrame
	 */

	public ExitFrame() {
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Metal".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(RemainingFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(RemainingFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(RemainingFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(RemainingFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		exitID = 0;
		pSpaceManage = new ParkSpaceManagement();
		bManage = new BillManagement();
		initComponents();
		jTextFieldExitID.setText(String.valueOf(exitID));
	}

	public ExitFrame(int eID, ParkSpaceManagement pm, BillManagement bm) {
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Metal".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(RemainingFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(RemainingFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(RemainingFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(RemainingFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		exitID = eID;
		pSpaceManage = pm;
		bManage = bm;
		initComponents();
		jTextFieldExitID.setText(String.valueOf(exitID));
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		java.awt.GridBagConstraints gridBagConstraints;

		jLabelID = new javax.swing.JLabel();
		jTextFieldExitID = new javax.swing.JTextField();
		jTextFieldID = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		jButtonLeave = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		getContentPane().setLayout(new java.awt.GridBagLayout());

		jLabelID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabelID.setText("Exit ID:");
		jLabelID.setFont(jLabelID.getFont().deriveFont(
				jLabelID.getFont().getSize() + 10f));
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.weightx = 0.3;
		gridBagConstraints.weighty = 0.1;
		gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
		getContentPane().add(jLabelID, gridBagConstraints);

		jTextFieldExitID.setEditable(false);
		jTextFieldExitID
				.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jTextFieldExitID.setFont(jTextFieldExitID.getFont().deriveFont(
				jTextFieldExitID.getFont().getSize() + 10f));
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.weightx = 0.7;
		gridBagConstraints.weighty = 0.1;
		gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
		getContentPane().add(jTextFieldExitID, gridBagConstraints);

		jTextFieldID.setFont(jTextFieldID.getFont().deriveFont(
				jTextFieldID.getFont().getSize() + 10f));
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.weightx = 0.5;
		gridBagConstraints.weighty = 0.2;
		gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
		getContentPane().add(jTextFieldID, gridBagConstraints);

		jLabel1.setText("input your parking bill id or car license:");
		jLabel1.setFont(jLabel1.getFont().deriveFont(
				jLabel1.getFont().getSize() + 5f));
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.gridwidth = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.weighty = 0.2;
		gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
		getContentPane().add(jLabel1, gridBagConstraints);

		jButtonLeave.setFont(jButtonLeave.getFont().deriveFont(
				jButtonLeave.getFont().getSize() + 10f));
		jButtonLeave.setText("Leave");
		jButtonLeave.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonLeaveActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.weightx = 0.5;
		gridBagConstraints.weighty = 0.2;
		gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
		getContentPane().add(jButtonLeave, gridBagConstraints);

		jTextArea1.setColumns(20);
		jTextArea1.setRows(10);
		jScrollPane1.setViewportView(jTextArea1);
		jTextArea1.setEditable(false);
		jTextArea1.setFont(jTextArea1.getFont().deriveFont(
				jTextArea1.getFont().getSize() + 5f));
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 3;
		gridBagConstraints.gridwidth = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.weighty = 0.5;
		gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
		getContentPane().add(jScrollPane1, gridBagConstraints);

		this.setTitle("Exit");
		pack();
	}// </editor-fold>

	private void jButtonLeaveActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		System.out.println("Button Tollbooth has been clicked.");
		if (jTextFieldID.getText().isEmpty()) {
			return;
		}
		BillDataBase bDat = new BillDataBase();
		int billID;
		try {
			billID = Integer.parseInt(jTextFieldID.getText().trim());
			bDat = bManage.getBillByBillID(billID);
		} catch (Exception e) {
			bDat = bManage.getBillByLicense(jTextFieldID.getText().trim());
		}
		// bDat = new BillDataBase();
		if (bDat == null) {
			JOptionPane.showMessageDialog(this, "No this Bill!", "Fail",
					JOptionPane.CLOSED_OPTION);
			System.out.println("No this bill.");
			return;
		}
		if (bDat.getStat() == 1) {
			bDat.setStat(2);
			pSpaceManage.leaveout();
			jTextArea1.append(bDat.getLeaveMessage());
			bManage.moveFromPaidListToCloseList(bDat.getBillID());
			bManage.saveAllBillDataToFile();
			JOptionPane.showMessageDialog(this, "Leave Success!", "Leava",
					JOptionPane.INFORMATION_MESSAGE);
		} else {
			JOptionPane.showMessageDialog(this, "Bill Stat Wrong!", "Fail",
					JOptionPane.CLOSED_OPTION);
			return;
		}
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		new ExitFrame().setVisible(true);
	}

	// Variables declaration - do not modify
	private javax.swing.JButton jButtonLeave;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabelID;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JTextField jTextFieldExitID;
	private javax.swing.JTextField jTextFieldID;
	private int exitID;
	private BillManagement bManage;
	private ParkSpaceManagement pSpaceManage;
	// End of variables declaration
}
