/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.ui;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;

import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;

import main.basedata.BillDataBase;
import main.maintain.BillManagement;

/**
 *
 * @author johnny
 */
public class StatsBillsFrame extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6843534264444444893L;

	/**
	 * Creates new form StatsBillsFrame
	 */
	public StatsBillsFrame() {
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Metal".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(RemainingFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(RemainingFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(RemainingFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(RemainingFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		Calendar calendar = Calendar.getInstance();// 日历对象
		calendar.setTime(new Date());
		this.monthBillManage = new BillManagement(
				sdf.format(calendar.getTime()) + ".dat");
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	@SuppressWarnings("serial")
	private void initComponents() {
		java.awt.GridBagConstraints gridBagConstraints;

		jLabelMonth = new javax.swing.JLabel();
		jLabelVISA = new javax.swing.JLabel();
		jLabelCash1 = new javax.swing.JLabel();
		jLabelTicket = new javax.swing.JLabel();
		jComboBoxMonth = new javax.swing.JComboBox();
		jTextFieldTicket = new javax.swing.JTextField();
		jTextFieldVISA = new javax.swing.JTextField();
		jTextFieldCash = new javax.swing.JTextField();
		jButtonLoad = new javax.swing.JButton();
		jButtonExit = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTableData = new javax.swing.JTable();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		getContentPane().setLayout(new java.awt.GridBagLayout());

		jLabelMonth.setText("Month:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.weightx = 0.3;
		gridBagConstraints.weighty = 0.1;
		gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
		getContentPane().add(jLabelMonth, gridBagConstraints);

		jLabelVISA.setText("VISA Count:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.weightx = 0.3;
		gridBagConstraints.weighty = 0.1;
		gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
		getContentPane().add(jLabelVISA, gridBagConstraints);

		jLabelCash1.setText("Cash Count:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 3;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.weightx = 0.3;
		gridBagConstraints.weighty = 0.1;
		gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
		getContentPane().add(jLabelCash1, gridBagConstraints);

		jLabelTicket.setText("TIcket Count:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.weightx = 0.3;
		gridBagConstraints.weighty = 0.1;
		gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
		getContentPane().add(jLabelTicket, gridBagConstraints);

		String[] month = new String[12];
		Date date = new Date();// 当前日期
		Calendar calendar = Calendar.getInstance();// 日历对象
		calendar.setTime(date);// 设置当前日期
		for (int i = 0; i < 12; i++) {
			month[i] = sdf.format(calendar.getTime());
			calendar.add(Calendar.MONTH, -1);// 月份减一
		}
		jComboBoxMonth.setModel(new javax.swing.DefaultComboBoxModel(month));
		jComboBoxMonth.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBoxMonthActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.weightx = 0.3;
		gridBagConstraints.weighty = 0.1;
		gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
		getContentPane().add(jComboBoxMonth, gridBagConstraints);

		jTextFieldTicket.setEditable(false);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.ipadx = 70;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.weightx = 0.3;
		gridBagConstraints.weighty = 0.1;
		gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
		getContentPane().add(jTextFieldTicket, gridBagConstraints);

		jTextFieldVISA.setEditable(false);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.ipadx = 70;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.weightx = 0.3;
		gridBagConstraints.weighty = 0.1;
		gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
		getContentPane().add(jTextFieldVISA, gridBagConstraints);

		jTextFieldCash.setEditable(false);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 3;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.ipadx = 70;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.weightx = 0.3;
		gridBagConstraints.weighty = 0.1;
		gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
		getContentPane().add(jTextFieldCash, gridBagConstraints);

		jButtonLoad.setText("Load");
		jButtonLoad.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonLoadActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 2;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.gridheight = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.weightx = 0.4;
		gridBagConstraints.weighty = 0.2;
		gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
		getContentPane().add(jButtonLoad, gridBagConstraints);

		jButtonExit.setText("Exit");
		jButtonExit.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonExitActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 2;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.gridheight = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.weightx = 0.4;
		gridBagConstraints.weighty = 0.2;
		gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
		getContentPane().add(jButtonExit, gridBagConstraints);

		jTableData
				.setModel(new DefaultTableModel(monthBillManage.getCellData(),
						monthBillManage.getColumnNames()) {
					@SuppressWarnings("rawtypes")
					Class[] types = new Class[] { java.lang.Integer.class,
							java.lang.String.class, java.lang.String.class,
							java.lang.String.class, java.lang.String.class,
							java.lang.Integer.class, java.lang.String.class,
							java.lang.Double.class };
					boolean[] canEdit = new boolean[] { false, false, false,
							false, false, false, false, false };

					public Class<?> getColumnClass(int columnIndex) {
						return types[columnIndex];
					}

					public boolean isCellEditable(int rowIndex, int columnIndex) {
						return canEdit[columnIndex];
					}
				});
		jScrollPane1.setViewportView(jTableData);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 4;
		gridBagConstraints.gridwidth = 3;
		gridBagConstraints.gridheight = 7;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.weighty = 0.4;
		gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
		getContentPane().add(jScrollPane1, gridBagConstraints);
		this.setTitle("Stats Bill");

		pack();
		jTextFieldTicket.setText(String.valueOf(monthBillManage
				.getTicketCount()));
		jTextFieldVISA.setText(String.valueOf(monthBillManage.getVisaCount()));
		jTextFieldCash.setText(String.valueOf(monthBillManage.getCashCount()));
	}// </editor-fold>

	private void jComboBoxMonthActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		System.out.println("Combo Box Month has been select!");
		monthBillManage = new BillManagement(jComboBoxMonth.getSelectedItem()
				+ ".dat");
	}

	private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		System.out.println("Button Exit has been clicked!");
		this.dispose();
	}

	private void jButtonLoadActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		System.out.println(jComboBoxMonth.getSelectedItem());
		Object[][] l = monthBillManage.getCellData();
		DefaultTableModel tableModel = (DefaultTableModel) this.jTableData
				.getModel();
		tableModel.setNumRows(0);
		for (Object[] p : l) {
			tableModel.addRow(p);
		}
		jTextFieldTicket.setText(String.valueOf(monthBillManage
				.getTicketCount()));
		jTextFieldVISA.setText(String.valueOf(monthBillManage.getVisaCount()));
		jTextFieldCash.setText(String.valueOf(monthBillManage.getCashCount()));

	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Create and display the form */
		new StatsBillsFrame().setVisible(true);
	}

	// Variables declaration - do not modify
	private javax.swing.JButton jButtonExit;
	private javax.swing.JButton jButtonLoad;
	private JComboBox jComboBoxMonth;
	private javax.swing.JLabel jLabelCash1;
	private javax.swing.JLabel jLabelMonth;
	private javax.swing.JLabel jLabelTicket;
	private javax.swing.JLabel jLabelVISA;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTableData;
	private javax.swing.JTextField jTextFieldCash;
	private javax.swing.JTextField jTextFieldTicket;
	private javax.swing.JTextField jTextFieldVISA;
	private BillManagement monthBillManage;
	private SimpleDateFormat sdf = BillDataBase.monthsdf;// 格式化对象
	// End of variables declaration
}
